version: 1

formatters:
  default:
    format: "{%(asctime)s: %(levelname)s - %(name)s - %(message)s}"
    datefmt: "%Y-%m-%dT%H:%M:%SZ"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    stream: ext://sys.stdout

  blank:
    class: logging.NullHandler
    formatter: default

loggers:
  bespoke:
    level: INFO
    handlers: [console]
    propagate: false

root:
  handlers: [console, blank]
  level: INFO